# OSX/Linux (https://github.com/travis-ci-tester/toolchain-table)

# Workaround for https://github.com/travis-ci/travis-ci/issues/8363
language:
  - minimal

# Container-based infrastructure (Linux)
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
sudo:
  - false

dist:
  - trusty

# Install packages differs for container-based infrastructure
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-do-I-install-APT-sources-and-packages%3F
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      # For Qt
      - libegl1-mesa-dev

      # For ogles_gpgpu (GL library)
      - libgl1-mesa-dev

      # Packages for Android development: http://superuser.com/a/360398/252568
      - libncurses5:i386
      - libstdc++6:i386
      - zlib1g:i386

      # Default GCC 4.8 is buggy:
      # * https://github.com/elucideye/drishti/issues/273#issuecomment-301297286
      - g++-5
      - gcc-5

      # pip3
      - python3-pip

matrix:
  include:
    # Linux {

    - os: linux
      env: CONFIG=Release TOOLCHAIN=gcc-5-pic-hid-sections-lto INSTALL=--strip

    # }

    # OSX {

    - os: osx
      env: CONFIG=Release TOOLCHAIN=osx-10-11-hid-sections-lto INSTALL=--install

    - os: osx
      osx_image: xcode8.1
      env: CONFIG=MinSizeRel TOOLCHAIN=ios-nocodesign-10-1-arm64-dep-9-0-device-libcxx-hid-sections-lto INSTALL=--install

    - os: osx
      osx_image: xcode8.1
      env: CONFIG=Release TOOLCHAIN=osx-10-12-sanitize-address-hid-sections INSTALL=--install

    - os: osx
      env: CONFIG=MinSizeRel TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon-hid-sections INSTALL=--strip

    # }

# disable the default submodule logic to support local modification of .gitmodules paths
git:
  submodules: false

# See https://docs.travis-ci.com/user/private-dependencies/#API-Token
# CI_USER_TOKEN is added to .travis.yml settings

install:
  - source bin/hunter_env.sh
  
script:
  - bin/drishti_build.sh "${TOOLCHAIN}" "${CONFIG}" "${INSTALL}"

before_deploy:
    - gem install mime-types -v 2.6.2 # workaround for https://github.com/travis-ci/travis-ci/issues/5145
    - export FILE_TO_UPLOAD=$(ls _archives/drishti-*.tar.gz)

deploy:
  provider: releases
  api_key:
    - secure: "erXHpMB4BJRRfK4Ksuo2Bw5X059m4MPi+lzlXMFgyidNc0R635dwxCnJE7oaA53wsqHw8WXjRjvrSHiPkKNABKTxDbYyA47wvk6wp2fV2yKVHYKIGs1sfAsHelC4j0QXrZoDb+dUu8pe7xalGQOhuR1HqevhLeQuFL+WlYGYMubJ2SKZCsnix7YXJdnkWHetKsp5WaUNZTAZTbg/wnKyhq21G+1Uh3Uy2oOzX1Y/no8vefxSxs3GFQPdY5H65naneFQ/qFv9f6xI14YaT47ULQ5IbNTL73Ov2+yUdqt2vcy9ZOSxtdmLfpBgIo9zjVuCgP3MxkDjfJM3DV+5CRLnDfyE+zC8wGB4vujN2LxcEEQcOXzHV+CPC5UKgD/pv/+EWrSCarVdW4DQciScGycmOQ/lOmeSDU1KQo3o5tTUELiBpZ17uOGSEnLRHiKz2vDfznWHg4WG0PTXlB28mqf49ohsu62BUmPqiv0DhOpPTsgK3bGGSTdpprPZUtxUX3fg1ui8qI1B82a1BdsDPKszebyVQn9QhpuCi/V5cHn8Zq4zR7i93pgL1t/sJwQ0ZAiEwjBm0uq1FLtJ9mnQfcXqvm4iqf4NU6e8tSHcszq/mquX3AxInS1fb3QZnVyymDz4ZC8uOUvA9KRMlff9e0LiFd0P7cCktByQAy4W94bsGFA="
  file_glob: true
  file: "${FILE_TO_UPLOAD}"
  skip_cleanup: true
  on:
    tags: true

branches:
  except:
    - /^pr\..*/
