# OSX/Linux (https://github.com/travis-ci-tester/toolchain-table)

# Workaround for https://github.com/travis-ci/travis-ci/issues/8363
language:
  - minimal

# Container-based infrastructure (Linux)
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
sudo:
  - false

dist:
  - trusty

# Install packages differs for container-based infrastructure
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-do-I-install-APT-sources-and-packages%3F
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      # For Qt
      - libegl1-mesa-dev

      # For ogles_gpgpu (GL library)
      - libgl1-mesa-dev

      # Packages for Android development: http://superuser.com/a/360398/252568
      - libncurses5:i386
      - libstdc++6:i386
      - zlib1g:i386

      # Default GCC 4.8 is buggy:
      # * https://github.com/elucideye/drishti/issues/273#issuecomment-301297286
      - g++-5
      - gcc-5

      - clang-5.0
      - libc++-dev
      - libc++abi-dev
      - libclang-5.0-dev
      - libclang-common-5.0-dev
      - libclang1-5.0

      # pip3
      - python3-pip

env:
  global:
    - secure: "mWyfa/K1aUKNn4JgwGh0wvH7KsZqFoldKeSgwERiHSLELAIeVLHXAznPDfj/s8SQKH0cLqq0QZcCVIfD7eMWterJSAFtuDl1L1UhMylNN92JE86xy1ISxeUkXKFRiAFDkKJkARvBGWH+k9mDJxqhdQwDtygLd0CpBebYIE92J7qelc5mSj08oB1H4tfJLAo5C/icinNE+XS2nr3QE2rYRFEjIEO6xhV7Dr4CL9ivUGC/8pH++bHWcmvxV6MPEePmLJfAN/Fz9z7mBQouHZDAryX4F3GMee5G4Dys+Fohqpsc4LBUXvYJ0KJW/F4vfeuI+WGaA86SFyP518kFY1ersxpT85cUpqqYkz3/xzV/eSpmSwJhGIuL/ZFSBQUSbGv8YIiP7cyZSpX/NFJzbD3gPoetFlhx3qoYX4UBIzMby/v4IRNaPTCUiFNE4ZFDC66R7AprSXxqxbEOaw+OjGyM8xn3XY9AYWAS2pGOD+ol3ppUiFVzw3WVJTHx1HrSOdDrJZicTnrGHOnCED2V4tnfO+s38V46BGjcYoTeOlH3FGyZqQiA/bqCyRU+84xc3tcL2mhnJLxAPwdD/f53pSaHs0ATODEx4WxCwR9Z+muy6lD6TO3TQIzVIsyy7VQT3sws3s7seKVvnGW3VhFYpKJYhXILa3ulqCMrVdDDzSqc9lw="

matrix:
  include:
    # Linux {

    - os: linux
      env: CONFIG=Release TOOLCHAIN=libcxx-fpic-hid-sections INSTALL=--strip

    - os: linux
      env: CONFIG=Release TOOLCHAIN=gcc-5-pic-hid-sections-lto INSTALL=--strip

    # }

    # OSX {

    - os: osx
      osx_image: xcode8.3
      env: CONFIG=Release TOOLCHAIN=osx-10-12-hid-sections INSTALL=--install

    - os: osx
      osx_image: xcode8.3
      env: CONFIG=MinSizeRel TOOLCHAIN=ios-nocodesign-10-3-arm64-dep-9-0-device-libcxx-hid-sections INSTALL=--install

    - os: osx
      osx_image: xcode8.3
      env: CONFIG=Release TOOLCHAIN=osx-10-12-sanitize-address-hid-sections INSTALL=--install

    - os: osx
      env: CONFIG=MinSizeRel TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon-hid-sections INSTALL=--strip

    # }

# disable the default submodule logic to support local modification of .gitmodules paths
git:
  submodules: false

# See https://docs.travis-ci.com/user/private-dependencies/#API-Token
# CI_USER_TOKEN is added to .travis.yml settings

before_install:

  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then mkdir -p latest-clang-symlinks && ln -s /usr/bin/clang-5.0 latest-clang-symlinks/clang && ln -s /usr/bin/clang++-5.0 latest-clang-symlinks/clang++ && export PATH="$PWD/latest-clang-symlinks:$PATH"; fi

install:
  - source bin/hunter_env.sh

script:
  - bin/drishti_build.sh "${TOOLCHAIN}" "${CONFIG}" "${INSTALL}"

before_deploy:
    - gem install mime-types -v 2.6.2 # workaround for https://github.com/travis-ci/travis-ci/issues/5145
    - export FILE_TO_UPLOAD=$(ls _archives/drishti-*.tar.gz)

deploy:
  provider: releases
  api_key:
    secure: "Ff1/kumLxjTf7ZND+yKJeZ8vS+jFCGPeXCFEIk3yZ8TiPxJmgmoMP56jWdR94WyAlqNroIvlAevSdtH/Lw7Qcu3MRcqFG64N7FBZz//UqpXZD4L12RcWDmtj8Jgk5t+Cty5nbuviYJ3sgk2Us4W0ykEE5Ot0E1M+oudWTuSDYihGlX7MEghyixxZCpO1uUYc16T8MHLus/NbBPONZsZ4UU3iUTojgqnhxc38gFmRSplk6FeFKL8JRZpZBXHgp/YdWTIpQWWvkQ1uRnk2l47n2pLTUPLyiIhG9o6WP9B5lGfvpiLGM/xUzmVYG09FZ6qM2R5oD+QHnQ+35oqhq/qTC+sg6yz1Lv4AXYQlhoS/yNne+w0E/N2Neh26oDEevPFQBltV25s6h7hZsjpGKNGNCDSXHEpV5Gn58C0E+dr6iTT20CbsT6zw/z1+n6z7OJlAuLLl0duKKsQ8pC3ngqHsn8OFmOYTtkAG6SU6mQZxMmJ5WlMwD85MlsEDIJwX/8dsW2aFSH5yPYiS0j6hbTQPD0lKYRr8czEzqPEd39A0yvwT81gQhcgoCDSui1jibd91paCFE9IpmV8YMPPV24GGlSKIqDWGbtacyuPXinQa+hW0bICqDfjh9nhRwBH9WqxjNBBZ09uX/8scke5pA3LcyfeXtmIAu4rHl7y8jU4B4WE="
  file_glob: true
  file: "${FILE_TO_UPLOAD}"
  skip_cleanup: true
  on:
    tags: true

branches:
  except:
    - /^pr\..*/
