# OSX/Linux (https://github.com/travis-ci-tester/toolchain-table)

# Workaround for https://github.com/travis-ci/travis-ci/issues/8363
language:
  - minimal

# Container-based infrastructure (Linux)
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
sudo:
  - false

dist:
  - trusty

# Install packages differs for container-based infrastructure
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-do-I-install-APT-sources-and-packages%3F
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      # For Qt
      - libegl1-mesa-dev

      # For ogles_gpgpu (GL library)
      - libgl1-mesa-dev

      # Packages for Android development: http://superuser.com/a/360398/252568
      - libncurses5:i386
      - libstdc++6:i386
      - zlib1g:i386

      # Default GCC 4.8 is buggy:
      # * https://github.com/elucideye/drishti/issues/273#issuecomment-301297286
      - g++-5
      - gcc-5

      # pip3
      - python3-pip

matrix:
  include:
    # Linux {

    - os: linux
      env: CONFIG=Release TOOLCHAIN=gcc-5-pic-hid-sections-lto INSTALL=--strip

    # }

    # OSX {

    - os: osx
      env: CONFIG=Release TOOLCHAIN=osx-10-11-hid-sections-lto INSTALL=--install

    - os: osx
      osx_image: xcode8.1
      env: CONFIG=MinSizeRel TOOLCHAIN=ios-nocodesign-10-1-arm64-dep-9-0-device-libcxx-hid-sections-lto INSTALL=--install

    - os: osx
      osx_image: xcode8.1
      env: CONFIG=Release TOOLCHAIN=osx-10-12-sanitize-address-hid-sections INSTALL=--install

    - os: osx
      env: CONFIG=MinSizeRel TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon-hid-sections INSTALL=--strip

    # }

# disable the default submodule logic to support local modification of .gitmodules paths
git:
  submodules: false

# See https://docs.travis-ci.com/user/private-dependencies/#API-Token
# CI_USER_TOKEN is added to .travis.yml settings

install:
  - source bin/hunter_env.sh
  
script:
  - bin/drishti_build.sh "${TOOLCHAIN}" "${CONFIG}" "${INSTALL}"

before_deploy:
    - gem install mime-types -v 2.6.2 # workaround for https://github.com/travis-ci/travis-ci/issues/5145
    - export FILE_TO_UPLOAD=$(ls _archives/drishti-*.tar.gz)

deploy:
  provider: releases
  api_key:
    - secure: "CSHxsBtjmJ3/z1ZqwnKMnso7Z67wZ2L4flYHjOMexwTxetNR8yVa+QbdxwXHFbEEQygSVIz1QO6K9AT+IU47+GI4UCmVvxLkxtxjARDSehIWvNC+7kpg3DmXLacJ1K0sY/bfjSxnUZBnKhJUIb5OetrK1sfYJmky2HyIXlvcepgPBtxR/BsORi3LYDUEMnbSlQljuVWm3zezCVpbUMo20cIw3vtSZz1ZrE5FgCzUl4ylTACqWGgDW4g4tDlusLb1ZzTfphfCGpiqLKAoydKGQbemUbFMiHFjYwZGCMbxMw0f9koL8eZCm03Mo+HoV+K1v87rhq+zRCnG5DI8UmZe3OW6oItS6wS1PuTex4SSL7xkcGq0kE2Zv1g9oVxO847kZ8g6Q/uPg7Nq9keJuH3elFcPs7cc8q9XfzXLgmeC3LAipqolPG3IQsAYl8yeoYbYCdyxCJeMotwDUB24TCRo79yQesRN+6VP1M+3frhL7wer5x6Bc/PwqW2oeOCfvoV3AtSBKHJuc3XknU1dff0Y8H0A0h8bOEK9zPi4qfR7/+IRyVqGW9nW4wPoq3wjlJgeP9nT28kQqtDDQik0a2GWcZGNONLP+pwkQ4c7en2awME8q/xLEvmfAiAoZQWwUEbHs4SNUBc9p82CdTfNjoeTfGxv12bbQhT8sM+ot+zfVJU="
  file_glob: true
  file: "${FILE_TO_UPLOAD}"
  skip_cleanup: true
  on:
    tags: true

branches:
  except:
    - /^pr\..*/
