image: Visual Studio 2015

environment:
  global:
    GITHUB_USER_PASSWORD:
      secure: x43zgAFmaHoqWwNDZEVzMvEWQSkHojfRWnVGMnmQziw9ozwrJTEnZdz5QD39bXMv

  matrix:

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      TOOLCHAIN: "vs-15-2017"
      CONFIG: Release
      BUILD_SHARED: ON

    - TOOLCHAIN: "vs-14-2015-sdk-8-1"
      CONFIG: Release
      BUILD_SHARED: OFF

    - TOOLCHAIN: "vs-14-2015-win64-sdk-8-1"
      CONFIG: Release
      BUILD_SHARED: OFF      

    - TOOLCHAIN: "vs-14-2015-win64-sdk-8-1"
      CONFIG: Debug
      BUILD_SHARED: OFF

install:
  # Python 3
  - cmd: set PATH=C:\Python34-x64;C:\Python34-x64\Scripts;%PATH%

  # Install Python package 'requests', 'gitpython'
  - cmd: pip install requests
  - cmd: pip install gitpython

  # Add '--quiet' to avoid leaking the token to logs
  - cmd: git submodule update --init --recursive --quiet

build_script:
  - cmd: python bin\jenkins.py

artifacts:
  - path: _archives\drishti-*.tar.gz
    name: Releases

deploy:
  provider: GitHub
  auth_token:
    secure: "x43zgAFmaHoqWwNDZEVzMvEWQSkHojfRWnVGMnmQziw9ozwrJTEnZdz5QD39bXMv"
  artifact: /drishti-.*\.tar.gz/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true

branches:
  except:
    - /^pr\..*/
