environment:
  matrix:

    - TOOLCHAIN: "vs-14-2015"
      CONFIG: Release

    - TOOLCHAIN: "vs-14-2015"
      CONFIG: Debug

    - TOOLCHAIN: "vs-14-2015-win64"
      CONFIG: Release

    - TOOLCHAIN: "vs-14-2015-win64"
      CONFIG: Debug

install:
  # Python 3
  - cmd: set PATH=C:\Python34-x64;C:\Python34-x64\Scripts;%PATH%

  # Install Python package 'requests'
  - cmd: pip install requests

  # Install latest Polly toolchains and scripts
  - cmd: appveyor DownloadFile https://github.com/ruslo/polly/archive/master.zip
  - cmd: 7z x master.zip
  - cmd: set POLLY_ROOT=%cd%\polly-master

  # Install dependencies (CMake, Ninja)
  - cmd: python %POLLY_ROOT%\bin\install-ci-dependencies.py

  - git submodule update --init --recursive

build_script:
  - cmd: call appveyor.cmd %POLLY_ROOT%\bin\polly.py% %CONFIG% %TOOLCHAIN%

artifacts:
  - path: _builds\*\drishti-*.tar.gz
    name: Releases

deploy:
  provider: GitHub
  auth_token:
    secure: "vxFB/5hNPqLZTSyiD3YxQVMXMmjrOyk8r/sp1GYsJ1T8o9v+wi3hjfl0W/ioSfW6"
  artifact: /drishti-.*\.tar.gz/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true

branches:
  except:
    - /^pr\..*/
