environment:

  global:
    CI_USER_TOKEN:
      secure: iJyVR7z6BkcqxkctwnDldPxLBNLKfO1qD3EchXiH0fimfDx1oq2gGQyfG4/NtfGX

  matrix:

    - TOOLCHAIN: "vs-14-2015-sdk-8-1"
      CONFIG: Release

    - TOOLCHAIN: "vs-14-2015-sdk-8-1"
      CONFIG: Debug

    - TOOLCHAIN: "vs-14-2015-win64-sdk-8-1"
      CONFIG: Release

    - TOOLCHAIN: "vs-14-2015-win64-sdk-8-1"
      CONFIG: Debug

install:
  # Python 3
  - cmd: set PATH=C:\Python34-x64;C:\Python34-x64\Scripts;%PATH%

  # Install Python package 'requests'
  - cmd: pip install requests

  # Install latest Polly toolchains and scripts
  - cmd: appveyor DownloadFile https://github.com/ruslo/polly/archive/master.zip
  - cmd: echo CHECK1
  - cmd: 7z x master.zip
  - cmd: echo CHECK2
  - cmd: set POLLY_ROOT=%cd%\polly-master
  - cmd: echo CHECK3

  # Install dependencies (CMake, Ninja)
  - cmd: python %POLLY_ROOT%\bin\install-ci-dependencies.py

  - cmd: echo CHECK4
    
  # Tune locations
  - cmd: set PATH=%cd%\_ci\cmake\bin;%PATH%
  - cmd: set PATH=%cd%\_ci\ninja;%PATH%

  - ps: (Get-Content .gitmodules).replace('https://github.com/elucideye/drishti-upload', 'https://' + ${Env:CI_USER_TOKEN} + '@github.com/elucideye/drishti-upload') | Set-Content .gitmodules

  - cmd: echo CHECK5
    
  # Add '--quiet' to avoid leaking the token to logs
  - cmd: git submodule update --init --recursive --quiet

  # Remove entry with sh.exe from PATH to fix error with MinGW toolchain
  # (For MinGW make to work correctly sh.exe must NOT be in your path)
  # * http://stackoverflow.com/a/3870338/2288008
  - cmd: set PATH=%PATH:C:\Program Files\Git\usr\bin;=%

  # Use MinGW from Qt tools because version is higher
  # * http://www.appveyor.com/docs/installed-software#qt
  - cmd: set MINGW_PATH=C:\Qt\Tools\mingw492_32\bin

  # MSYS2 location
  - cmd: set MSYS_PATH=C:\msys64\usr\bin

  - cmd: echo OK HERE

build_script:
  - bin\build-appveyor.cmd %CONFIG% %TOOLCHAIN%

artifacts:
  - path: _archives\drishti-*.tar.gz
    name: Releases

deploy:
  provider: GitHub
  auth_token:
    secure: "iJyVR7z6BkcqxkctwnDldPxLBNLKfO1qD3EchXiH0fimfDx1oq2gGQyfG4/NtfGX"
  artifact: /drishti-.*\.tar.gz/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true

branches:
  except:
    - /^pr\..*/
