image: Visual Studio 2015

environment:

  global:
    CI_USER_TOKEN:
      secure: "aS2ZbXuGLbgWTUO3GxtirbFiE6jpBkAs073X8D/URg7Snw2NPBENvmJiWxZfDeTV"

  matrix:

    - TOOLCHAIN: "vs-14-2015-sdk-8-1"
      CONFIG: Release

    - TOOLCHAIN: "vs-14-2015-sdk-8-1"
      CONFIG: Debug

    - TOOLCHAIN: "vs-14-2015-win64-sdk-8-1"
      CONFIG: Release

    - TOOLCHAIN: "vs-14-2015-win64-sdk-8-1"
      CONFIG: Debug

install:
  - cmd: bin\hunter_env.cmd

build_script:

  - cmd: bin\build-appveyor.cmd "%CONFIG%" "%TOOLCHAIN%"

artifacts:
  - path: _archives\drishti-*.tar.gz
    name: Releases

deploy:
  provider: GitHub
  auth_token:
    secure: "iJyVR7z6BkcqxkctwnDldPxLBNLKfO1qD3EchXiH0fimfDx1oq2gGQyfG4/NtfGX"
  artifact: /drishti-.*\.tar.gz/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true

branches:
  except:
    - /^pr\..*/
